env:
  browser: true
  es6: true
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
extends: ["standard", "plugin:vue/recommended"]
rules:
  brace-style: 1
  comma-dangle: ["error", "always-multiline"]
  indent: ["error", 2]
  no-console: 0
  no-unused-vars: 1
  quotes: ["error", "single"]
  semi: ["error", "never"]
  vue/html-self-closing: 0
  vue/max-attributes-per-line: 0
  vue/singleline-html-element-content-newline: 0
